apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    service: kafka
spec:
  replicas: 1 # TODO: shard by partitions
  selector:
    matchLabels:
      service: kafka
  template:
    metadata:
      labels:
        service: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6.1
          env:
            - name: KAFKA_BROKER_ID
              value: 1
            - name: KAFKA_CFG_LISTENERS
              value: CLIENT://:9092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CLIENT:PLAINTEXT
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: CLIENT://kafka.default.svc.cluster.local:9092
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: CLIENT
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper.default.svc.cluster.local:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          readinessProbe:
            exec:
              command:
                - kafka-topics.sh
                - --list
                - --bootstrap-server
                - localhost:9092
            initialDelaySeconds: 8
            periodSeconds: 30

        - name: zookeeper
          image: bitnami/zookeeper:3.8.3
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    service: producer
spec:
  replicas: 1 # TODO: shard by partitions
  selector:
    matchLabels:
      service: producer
  template:
    metadata:
      labels:
        service: producer
    spec:
      containers:
        - name: producer
          image: knative-kafka-cloudevents-producer:latest
          env:
            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local:9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    service: consumer
spec:
  replicas: 1 # TODO: shard by partitions
  selector:
    matchLabels:
      service: consumer
  template:
    metadata:
      labels:
        service: consumer
    spec:
      containers:
        - name: consumer
          image: knative-kafka-cloudevents-consumer:latest
          env:
            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local:9092
